version = 0.1
[default.deploy.parameters]
stack_name = "fit-track"
resolve_s3 = true
s3_prefix = "fit-track"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "FirebaseCredentialsSecret=\"FitTrackFirebaseCredentials\""
