AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  FitTrack Backend

  SAM Template for FitTrack application

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.9 # Or choose another runtime like nodejs18.x, java11 etc.
    Architectures:
      - x86_64

Resources:
  FirebaseAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth-function/
      Handler: app.lambda_handler
      Environment:
        Variables:
          FIREBASE_CREDENTIALS: !Sub '{{resolve:secretsmanager:${FirebaseCredentialsSecret}}}'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'secretsmanager:GetSecretValue'
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${FirebaseCredentialsSecret}'

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambda_handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            Auth:
              Authorizer: FirebaseAuthorizer

Parameters:
  FirebaseCredentialsSecret:
    Type: String
    Description: Name of the AWS Secrets Manager secret containing Firebase credentials

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn 